# Generated by Django 2.1.11 on 2019-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_deactivateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivateuser',
            name='deactive',
            field=models.BooleanField(default=True),
        ),
    ]
