# Generated by Django 2.1.11 on 2019-09-06 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20190906_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivateuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate', to=settings.AUTH_USER_MODEL),
        ),
    ]
