# Generated by Django 2.1.11 on 2019-09-13 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20190906_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to=settings.AUTH_USER_MODEL),
        ),
    ]
