# Generated by Django 2.1.11 on 2020-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_nationalidimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalidimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
