# Generated by Django 2.1.11 on 2020-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190919_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
