# Generated by Django 2.1.11 on 2019-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('r', 'read'), ('u', 'unread')], default='u', max_length=1),
        ),
    ]
