# Generated by Django 2.1.11 on 2019-09-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190822_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='seller',
        ),
    ]
