# Generated by Django 2.1.11 on 2020-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productviews',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
